### ISSUE TITLE
Add index.yml

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [chpc-uofu/OOD-apps-v3#3]
To aid in automation, create an `index.yml` file using the following structure:
```yaml
apiVersion: v1
entries:
  appname: []
  anotherappname: []
```
The empty arrays leave room for possible future attribution.
